// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmeWHLUtqQkj3_1NSswcUdn52P5Q0S4xU',
    appId: '1:784493758629:web:ff2a2d3ad606cc3f90254c',
    messagingSenderId: '784493758629',
    projectId: 'gas-station-99051',
    authDomain: 'gas-station-99051.firebaseapp.com',
    databaseURL: 'https://gas-station-99051-default-rtdb.firebaseio.com',
    storageBucket: 'gas-station-99051.firebasestorage.app',
    measurementId: 'G-9LJ59DM6BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg_4XJUS0N9o4wuqL38SwC78Q7Lfz95qM',
    appId: '1:784493758629:android:70e620834a3b840490254c',
    messagingSenderId: '784493758629',
    projectId: 'gas-station-99051',
    databaseURL: 'https://gas-station-99051-default-rtdb.firebaseio.com',
    storageBucket: 'gas-station-99051.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeGPD68tqGQbsuKlyZfBgz9wRZphMn4Nk',
    appId: '1:784493758629:ios:84e8716bc4a4e74690254c',
    messagingSenderId: '784493758629',
    projectId: 'gas-station-99051',
    databaseURL: 'https://gas-station-99051-default-rtdb.firebaseio.com',
    storageBucket: 'gas-station-99051.firebasestorage.app',
    iosBundleId: 'com.example.gasStations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeGPD68tqGQbsuKlyZfBgz9wRZphMn4Nk',
    appId: '1:784493758629:ios:84e8716bc4a4e74690254c',
    messagingSenderId: '784493758629',
    projectId: 'gas-station-99051',
    databaseURL: 'https://gas-station-99051-default-rtdb.firebaseio.com',
    storageBucket: 'gas-station-99051.firebasestorage.app',
    iosBundleId: 'com.example.gasStations',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmeWHLUtqQkj3_1NSswcUdn52P5Q0S4xU',
    appId: '1:784493758629:web:fcfa7d349ae2cf9590254c',
    messagingSenderId: '784493758629',
    projectId: 'gas-station-99051',
    authDomain: 'gas-station-99051.firebaseapp.com',
    databaseURL: 'https://gas-station-99051-default-rtdb.firebaseio.com',
    storageBucket: 'gas-station-99051.firebasestorage.app',
    measurementId: 'G-W2X2VX54C4',
  );
}
